export const signalLights = {
    BLUE_UP_SOLID: 'images/signals/blue-up-solid.svg',
    GREEN_DOWN_BLINKING: 'images/signals/green-down-blinking.svg',
    GREEN_DOWN_SOLID: 'images/signals/green-down-solid.svg',
    GREEN_MIDDLE_BLINKING: 'images/signals/green-middle-blinking.svg',
    GREEN_MIDDLE_SOLID: 'images/signals/green-middle-solid.svg',
    GREEN_UP_BLINKING: 'images/signals/green-up-blinking.svg',
    GREEN_UP_SOLID: 'images/signals/green-up-solid.svg',
    OFF_DOWN: 'images/signals/off-down.svg',
    OFF_MIDDLE: 'images/signals/off-middle.svg',
    OFF_UP: 'images/signals/off-up.svg',
    ORANGE_DOWN_BLINKING: 'images/signals/orange-down-blinking.svg',
    ORANGE_DOWN_SOLID: 'images/signals/orange-down-solid.svg',
    ORANGE_MIDDLE_BLINKING: 'images/signals/orange-middle-blinking.svg',
    ORANGE_MIDDLE_SOLID: 'images/signals/orange-middle-solid.svg',
    ORANGE_UP_BLINKING: 'images/signals/orange-up-blinking.svg',
    ORANGE_UP_SOLID: 'images/signals/orange-up-solid.svg',
    POLE: 'images/signals/pole.svg',
    POLE_SP: 'images/signals/pole-sp.svg',
    POLE_TO: 'images/signals/pole-to.svg',
    POLE_TM: 'images/signals/pole-tm.svg',
    RED_MIDDLE_SOLID: 'images/signals/red-middle-solid.svg',
    RED_UP_SOLID: 'images/signals/red-up-solid.svg',
    WHITE_DOWN_BLINKING: 'images/signals/white-down-blinking.svg',
    WHITE_DOWN_SOLID: 'images/signals/white-down-solid.svg',
};
